name: Publish to PyPI

on:
  release:
    types: [published]
    branches: [main]

jobs:
  build:
    name: Build distribution and verify version
    uses: ./.github/workflows/build-and-verify.yml
    with:
      python-version: "3.10"

  publish-pypi:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    # Publish to PyPI only when ALL of the following conditions are met:
    # 1. github.event.release.prerelease == false: The release is NOT marked as prerelease
    # 2. startsWith(github.ref, 'refs/tags/'): The workflow is triggered by a tag push
    # This ensures only stable releases from tags go to production PyPI
    if: github.event.release.prerelease == false && startsWith(github.ref, 'refs/tags/')
    environment: 
      name: pypi
      url: https://pypi.org/p/simple-global-logging
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 