name: Publish to TestPyPI

on:
  release:
    types: [published]
    branches-ignore: [main]

jobs:
  build:
    name: Build distribution and verify version
    uses: ./.github/workflows/build-and-verify.yml
    with:
      python-version: "3.10"

  publish-testpypi:
    name: Upload release to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    # Publish to TestPyPI only when ALL of the following conditions are met:
    # 1. github.event.release.prerelease == true: The release is marked as prerelease
    # 2. startsWith(github.ref, 'refs/tags/'): The workflow is triggered by a tag push
    # This ensures only prerelease versions from tags go to TestPyPI
    if: github.event.release.prerelease == true && startsWith(github.ref, 'refs/tags/')
    environment: 
      name: testpypi
      url: https://test.pypi.org/p/simple-global-logging
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true 